name: get proxy ip

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  download-filter-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download alive.txt
        run: |
          curl -o alive.txt https://raw.githubusercontent.com/Mayumiwandi/Emilia/refs/heads/main/Data/alive.txt

      - name: Copy alive.txt to ALL.txt
        run: |
          cp alive.txt ALL.txt

      - name: Filter proxies by country code
        run: |
          # Create a list of unique country codes from the downloaded file.
          COUNTRY_CODES=$(cut -d',' -f3 alive.txt | sort | uniq | tail -n +2 | sed '/^$/d')

          echo "Found country codes: $COUNTRY_CODES"
          
          # Loop through each unique country code.
          for CODE in $COUNTRY_CODES; do
            # Filter lines containing the country code and save to a new file.
            grep -E ",$CODE," alive.txt > "$CODE.txt"
          done

      - name: Add filtered files to staging area
        run: |
          git add ALL.txt *.txt
      
      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git diff --staged)" ]; then
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit and push if changes exist
        if: steps.git-check.outputs.changes_exist == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update proxy lists with latest data by country code"
          git push
