name: get proxy ip ID and SG

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  download-filter-and-commit:
    runs-on: ubuntu-latest
    permissions:
      # Add this line to give the bot 'write' permission for repository contents.
      contents: write

    steps:
      - name: Checkout repository
        # Use v4 for a more stable and updated action.
        uses: actions/checkout@v4

      - name: Download alive.txt
        run: |
          curl -o alive.txt https://raw.githubusercontent.com/Mayumiwandi/Emilia/refs/heads/main/Data/alive.txt

      - name: Filter for ID and SG proxies
        # Redirect output to a new file, overwriting it if it exists.
        run: |
          grep -E ',ID,|,SG,' alive.txt > proxy_ip.txt
      
      - name: Add proxy_ip.txt to staging area
        # Add the file to the staging area to check for changes
        run: |
          git add proxy_ip.txt
      
      - name: Check for changes
        id: git-check
        run: |
          # Use 'git diff --staged' to check for changes in the staging area.
          if [ -n "$(git diff --staged)" ]; then
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit and push if changes exist
        if: steps.git-check.outputs.changes_exist == 'true'
        run: |
          # Set the bot's identity for the commit.
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # The file is already in the staging area from the previous step.
          git commit -m "Update proxy_ip.txt with latest ID and SG proxies"
          
          # Push the changes to the remote repository.
          git push
